spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core: INFO

services:
  user-service:
    host: http://localhost
    port: 8080
  project-service:
    host: http://localhost
    port: 8082

account:
  batch-size: 5
  number:
    length: 16
  generate:
    cron: "* 7 * * * *"

savings_account:
  interest_calculation:
    cron: "0 0 0 * * ?"
    thread_pool: 10