spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8091

services:
  user-service:
    name: user-service
    host: http://localhost
    port: 8080
  project-service:
    name: project-service
    host: http://localhost
    port: 8082
  s3:
    endpoint: http://127.0.0.1:9000/
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    targetWidth: 1080
    targetHeight: 566
    maxFilesAmount: 10

logging:
  level:
    root: info

api:
  version: v1

servlet:
  multipart:
    max-file-size: 5MB

