spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-checksums: true
server:
  port: 8090

account-service:
  account-numbers:
    max-number-of-free-accounts: 10
    min-number-of-free-accounts: 1
    max-length-of-account-number: 20


project-service:
  host: localhost
  port: 8082

user-service:
  host: localhost
  port: 8080
  path: user-service


logging:
  level:
    root: info
