spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

logging:
  level:
    root: info

app:
  async:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 500
    threadNamePrefix: "AsyncExecutor-"
  scheduling:
    free_account_number:
      cron: "0 0 12 * * ?"
    balance_update:
      cron: "0 0 10 * * ?"
  account:
    prefixes:
      savings_account: "8800"
    max_quantity: 100