spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      topic: payment_transaction_DMS
      client-id: payment_service_DMS

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

logging:
  level:
    root: info

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080