spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        account_channel:
          name: account_channel

server:
  port: 8090

logging:
  level:
    root: info

accrual :
  executors-pool: 20
  size-select-db: 50000
  accrual-run-size: 1000

project-service:
  host: localhost
  port: 8082
  url: localhost:8082/api/v1
user-service:
  host: localhost
  port: 8080
  url: localhost:8080/api/v1

account-generation:
  amountToGenerate: 500
  retryDelay: 3000

account-executor:
  unique-batch: 100
  thread-pool-size: 5
  thread-queue: 100