spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

logging:
  level:
    root: info

interest:
  accrual:
    days: 365
    hours: 24

scheduled:
  task:
    cronForAccrual: "0 0 0 * * *"
    cronForGenerateNumbers: "0 0 * * * *"

poolThreads:
  poolForAccrual: 10