spring:
  mvc:
    servlet:
      path: /api/v1  # Set default path for Spring MVC controllers

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

services:
  user-service:
    name: user-service
    host: http://localhost
    port: 8080
  project-service:
    name: project-service
    host: http://localhost
    port: 8082



logging:
  level:
    root: info
