spring:
  datasource:
    tomcat:
      connection-properties: stringtype=unspecified
    hikari:
      data-source-properties:
        stringtype: unspecified
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8090

scheduler:
  cron:
    request: "0 */2 * * * *"

logging:
  level:
    root: info
