name: CI

on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'basilisk-master-stream6'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
       - run:
           ./gradlew clean build -x test
         with:
          java-version: 17