name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
        with:
          java-version: 17
        run: ./gradlew clean build -x test